---
title: Introduction to Processing
hero_image: images/banner.png
description: Learn how to create graphics with code in Processing
original_url: https://raspberrypi.org/learning/introduction-to-processing
theme: red
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: electronic-components
site_areas: projects
hardware: electronic-components
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
- title: Write your first Processing sketch
- title: Draw other shapes
  completion:
  - engaged
- title: Add colour
- title: Respond to the mouse
- title: Make things move
- title: Controlling an LED
- title: React to a button
  completion:
  - internal
- title: What next?
