---
title: Introduction to Processing
hero_image: images/banner.png
description: Learn how to create graphics with code in Processing
original_url: https://raspberrypi.org/learning/introduction-to-processing
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: builder, design-0, programming-2, phys-comp-1, manufacture-0, community-0
interests: ''
technologies: physical computing, processing
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Write your first Processing sketch
- title: Draw other shapes
- title: Add colour
- title: Respond to the mouse
- title: Make things move
- title: Controlling an LED
- title: React to a button
- title: What next?
